import { Floor } from "../types"

export const keys = [
  {
    color: "#8d65e0",
    title: "Resources",
  },
  {
    color: "#dc4b7c",
    title: "Labs/Study/Areas",
  },
  {
    color: "#6584c7",
    title: "Classrooms",
  },
  {
    color: "#7cbf7f",
    title: "Staff",
  }
]

export const floors: Floor[] = [
  {
    id: 1,
    points: [
      //! Resources
      {
        title: "Ground Level Stacks",
        subtitle: "Books and Multimedia",
        office: "Stacks",
        key: "Resources",
      },
      {
        title: "Microfilm",
        subtitle: "Microfilm Viewing Machine",
        description: "Point Description Lorem Isupm dollar.",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["6:30AM", "10:30PM"],
        office: "MFLM",
        key: "Resources",
      },
      //! Lab & Study Areas
      {
        title: "Mule Works Lab",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        office: "007D",
        key: "Labs/Study/Areas",
        formattedKey: "Labs & Study Areas",
      },
      {
        title: "Hall Study Area",
        subtitle: "Open Space for Study",
        office: "007D",
        key: "Labs/Study/Areas",
        formattedKey: "Labs & Study Areas",
      },
      {
        title: "Special Collections Processing",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        office: "SCP",
        key: "Labs/Study/Areas",
        formattedKey: "Labs & Study Areas",
      },
      {
        title: "Study Rooms 20A-D",
        subtitle: "Study Rooms",
        office: "020A-D",
        key: "Labs/Study/Areas",
        formattedKey: "Labs & Study Areas",
      },
      {
        title: "Room 005",
        subtitle: "Digital Production Center",
        office: "005",
        key: "Labs/Study/Areas",
        formattedKey: "Labs & Study Areas",
      },
      //! Classrooms
      {
        title: "Classroom 008",
        subtitle: "Multi-use Classroom",
        office: "008",
        key: "Classrooms",
      },
      {
        title: "Classroom 014",
        subtitle: "Multi-use Classroom",
        office: "014",
        key: "Classrooms",
      },
      {
        title: "Seminar Room",
        subtitle: "Open Space for Study",
        office: "034",
        key: "Classrooms",
      },
      //! Staff Directory
      {
        title: "Darylyne Provost",
        subtitle: "Assistant Director for Digital Initiatives",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        office: "007B",
        gender: "female",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
      {
        title: "Mike McGuire",
        subtitle: "Systems and Emerging Technologies Librarian",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        office: "007C",
        gender: "male",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
      {
        title: "Mike Jandreau",
        subtitle: "Library Web Developer",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        office: "007D",
        gender: "male",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
      {
        title: "Matt LeVan",
        subtitle: "Digital Archives and Exhibitions Librarian",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        office: "007A",
        gender: "male",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
      {
        title: "Eileen Richards",
        subtitle: "Systems Coordinator",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        office: "005B",
        gender: "male",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
      {
        title: "Martin Kelly",
        subtitle: "Digital Collections Librarian",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        office: "005A",
        gender: "male",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
      {
        title: "Room 009",
        subtitle: "Colby Cares About Kids",
        office: "009",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
      {
        title: "Room 009A",
        subtitle: "Colby Cares About Kids",
        office: "009A",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
      {
        title: "Ana Noriega",
        subtitle: "Assistant Director for Collections Management",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        office: "004A",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        gender: "female",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
      {
        title: "Katie Donahue",
        subtitle: "Technical Services and Metadata Librarian",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        office: "004B",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        gender: "female",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
      {
        title: "Room 004",
        subtitle: "Colby Cares About Kids",
        office: "004",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        key: "Staff",
        formattedKey: "Staff Directory",
      },
      {
        title: "Bess Stokes",
        subtitle: "Visiting Assistant Professor of Writing",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        office: "028",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        gender: "female",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
      {
        title: "Lauren Yoshizawa",
        subtitle: "Pre-doctoral Fellow in Education",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        office: "0035",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        gender: "female",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
      {
        title: "Celeste Cessaro",
        subtitle: "Administrative Assistant",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        office: "0039",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        gender: "female",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
      {
        title: "David Casalaspi",
        subtitle: "Visiting Assistant Professor of Education",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        office: "0038",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        gender: "female",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
      {
        title: "Lyn Brown & Mark Tappan",
        subtitle: "Professor and Director",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        office: "0037",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        gender: "female",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
      {
        title: "Adam Howard",
        subtitle: "Professor of Education Program Director",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        office: "0036",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        gender: "female",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
    ]
  },
  {
    id: 2,
    points: [
      //! Resources
      {
        title: "Service Desk",
        key: "Resources",
      },
      {
        title: "First Floor Stacks",
        description: "Point Description Lorem Isupm dollar.",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        office: "007D",
        key: "Resources",
      },
      {
        title: "New Books",
        office: "NB",
        key: "Resources",
      },
      {
        title: "Colby Authors",
        subtitle: "Books by Colby Alumni",
        office: "NB",
        key: "Resources",
      },
      {
        title: "Reference Books",
        office: "134",
        key: "Resources",
      },
      {
        title: "Periodicals",
        office: "134",
        key: "Resources",
      },
      //! Labs & Study Areas
      {
        title: "Special Collections",
        subtitle: "Reading Rooms and Resources",
        office: "SC",
        key: "Labs/Study/Areas",
        formattedKey: "Labs & Study Areas",
      },
      {
        title: "Special Collections",
        subtitle: "Reading Rooms and Resources",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita iste fuga veniam consectetur voluptates laborum quo maxime error ullam dicta provident vero culpa optio est voluptatem, magnam omnis quos amet?",
        office: "134",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        key: "Labs/Study/Areas",
        formattedKey: "Labs & Study Areas",
      },
      {
        title: "Chapman Room",
        office: "113",
        key: "Labs/Study/Areas",
        formattedKey: "Labs & Study Areas",
      },
      {
        title: "Robinson Room",
        office: "108",
        key: "Labs/Study/Areas",
        formattedKey: "Labs & Study Areas",
      },
      {
        title: "Healy Room",
        office: "119",
        key: "Labs/Study/Areas",
        formattedKey: "Labs & Study Areas",
      },
      {
        title: "Wormser Room",
        office: "115",
        key: "Labs/Study/Areas",
        formattedKey: "Labs & Study Areas",
      },
      {
        title: "Fit Lab",
        subtitle: "Multipurpose Meeting Space",
        office: "105",
        key: "Labs/Study/Areas",
        formattedKey: "Labs & Study Areas",
      },
      //! Classrooms
      {
        title: "Special Collections",
        subtitle: "Reading Rooms and Resources",
        office: "104",
        key: "Labs/Study/Areas",
      },
      //! Staff Directory
      {
        title: "Rachel Gammon",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        office: "130",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        gender: "female",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
      {
        title: "Ellen Freeman",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        office: "106B",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["7:30AM", "11:30PM"],
        gender: "female",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
      {
        title: "Mark Wardecker",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        office: "106",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        gender: "male",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
      {
        title: "Tim Stonsifer",
        subtitle: "Instructional Technologist: Video Production Specialist",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        office: "102",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        gender: "male",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
      {
        title: "Lareese Hall",
        subtitle: "Director of the Colby Libraries",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        office: "101",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        gender: "male",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
      {
        title: "April Paul",
        subtitle: "Library Assistant",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        office: "129",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        gender: "male",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
      {
        title: "Stacey Sheriff",
        subtitle: "Director of Colby Writing Program",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        office: "106D",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        gender: "male",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
      {
        title: "Carol Hurney",
        subtitle: "Director of the Center for Teaching and Learning",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        office: "106C",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        gender: "male",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
      {
        title: "Jason Parkhill",
        subtitle: "Director of Academic Information Technology Services",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        office: "106A",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        gender: "male",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
      {
        title: "Karen Gillum",
        subtitle: "NAME_TITLE",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        office: "107",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        gender: "male",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
      {
        title: "Bonnie Paige",
        subtitle: "NAME_TITLE",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        office: "107A",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        gender: "male",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
      {
        title: "Marilyn Pukkila",
        subtitle: "NAME_TITLE",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        office: "107B",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        gender: "male",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
      {
        title: "Laine Thielstrom",
        subtitle: "NAME_TITLE",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        office: "107C",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        gender: "male",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
      {
        title: "Stephanie Frost",
        subtitle: "NAME_TITLE",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque debitis, aliquid quasi distinctio! Suscipit quia itaque perspiciatis laboriosam dolores voluptates fugit a. Dolorum, pariatur quas. Cupiditate expedita odit, recusandae aut.",
        office: "107D",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        gender: "male",
        key: "Staff",
        formattedKey: "Staff Directory",
      },
    ]
  },
  {
    id: 3,
    points: [
      //! Resources
      {
        title: "Second Floor Stacks",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed ad expedita soluta nesciunt dignissimos beatae vero eius unde dicta adipisci officia, quis eos iusto quidem ratione iure aspernatur, ea eaque.",
        office: "Stacks",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["6:30AM", "9:30PM"],
        key: "Resources",
      },
      //! Labs & Study Areas
      {
        title: "Second Floor Study Area",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat culpa modi nam consequuntur tempora, mollitia eveniet quas alias facere incidunt et, fugit nemo pariatur quia, quasi neque molestias hic maiores.",
        office: "Hall",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "11:30PM"],
        key: "Labs/Study/Areas",
        formattedKey: "Labs & Study Areas",
      },
      {
        title: "Farnham Writing Center",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id deleniti iste quis, hic perferendis ratione vero! Facilis debitis repellendus expedita fuga porro, placeat voluptatum sapiente dignissimos corporis voluptate quia praesentium.",
        office: "206",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["10:00AM", "Midnight Sun-Thu"],
        key: "Labs/Study/Areas",
        formattedKey: "Labs & Study Areas",
      },
      //! Classrooms
      {
        title: "Room 205",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id deleniti iste quis, hic perferendis ratione vero! Facilis debitis repellendus expedita fuga porro, placeat voluptatum sapiente dignissimos corporis voluptate quia praesentium.",
        office: "205",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        key: "Classrooms",
      },
      {
        title: "Room 205",
        office: "208",
        key: "Classrooms",
      },
      //! Staff Directory
      {
        title: "Meghan Hancock",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium architecto reiciendis modi, odio reprehenderit accusamus pariatur officiis distinctio neque velit doloribus error, impedit quisquam tempore possimus, eos temporibus laudantium culpa?",
        office: "207A",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        key: "Labs/Study/Areas",
        formattedKey: "Labs & Study Areas",
      },
      {
        title: "Ghada Gherwash",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium architecto reiciendis modi, odio reprehenderit accusamus pariatur officiis distinctio neque velit doloribus error, impedit quisquam tempore possimus, eos temporibus laudantium culpa?",
        office: "207B",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        key: "Labs/Study/Areas",
        formattedKey: "Labs & Study Areas",
      },
      {
        title: "Jordan Bailey",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium architecto reiciendis modi, odio reprehenderit accusamus pariatur officiis distinctio neque velit doloribus error, impedit quisquam tempore possimus, eos temporibus laudantium culpa?",
        office: "207C",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        key: "Labs/Study/Areas",
        formattedKey: "Labs & Study Areas",
      },
      {
        title: "Kerrill O'Neil",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium architecto reiciendis modi, odio reprehenderit accusamus pariatur officiis distinctio neque velit doloribus error, impedit quisquam tempore possimus, eos temporibus laudantium culpa?",
        office: "200",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        key: "Labs/Study/Areas",
        formattedKey: "Labs & Study Areas",
      },
      {
        title: "Megan Fossa",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium architecto reiciendis modi, odio reprehenderit accusamus pariatur officiis distinctio neque velit doloribus error, impedit quisquam tempore possimus, eos temporibus laudantium culpa?",
        office: "201",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        key: "Labs/Study/Areas",
        formattedKey: "Labs & Study Areas",
      },
      {
        title: "Paula Harrington",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium architecto reiciendis modi, odio reprehenderit accusamus pariatur officiis distinctio neque velit doloribus error, impedit quisquam tempore possimus, eos temporibus laudantium culpa?",
        office: "202",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        key: "Labs/Study/Areas",
        formattedKey: "Labs & Study Areas",
      },
      {
        title: "FWC Tutor Office",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium architecto reiciendis modi, odio reprehenderit accusamus pariatur officiis distinctio neque velit doloribus error, impedit quisquam tempore possimus, eos temporibus laudantium culpa?",
        office: "203A",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        key: "Labs/Study/Areas",
        formattedKey: "Labs & Study Areas",
      },
      {
        title: "Carolyn Megan",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium architecto reiciendis modi, odio reprehenderit accusamus pariatur officiis distinctio neque velit doloribus error, impedit quisquam tempore possimus, eos temporibus laudantium culpa?",
        office: "203B",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        key: "Labs/Study/Areas",
        formattedKey: "Labs & Study Areas",
      },
    ],
  },
  {
    id: 4,
    points: [
      //! Resources
      {
        title: "Third Floor Stacks",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita nulla pariatur amet id ipsam similique saepe beatae quasi aliquid. Eos fugit esse nesciunt similique maxime, architecto totam ducimus placeat consequatur?",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["7:30AM", "11:30PM"],
        office: "Stacks",
        key: "Resources", position: [0, 1.35, 0.35],
      },
      //! Labs & Study Areas
      {
        title: "Third Floor Study Area",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat culpa modi nam consequuntur tempora, mollitia eveniet quas alias facere incidunt et, fugit nemo pariatur quia, quasi neque molestias hic maiores.",
        office: "Hall",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "11:30PM"],
        key: "Labs/Study/Areas",
        formattedKey: "Labs & Study Areas", position: [0.95, 0.2, 0.35,],
      },
      //! Classrooms
      {
        title: "Room 305 A",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Provident inventore molestias ad quisquam officiis cupiditate itaque sed id quasi quo eveniet, quam unde laboriosam nam voluptatum vero odio ullam omnis!",
        office: "305A",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        key: "Classrooms", position: [-1.4, 0.25, 0.35,],
      },
      {
        title: "Room 305 B",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Provident inventore molestias ad quisquam officiis cupiditate itaque sed id quasi quo eveniet, quam unde laboriosam nam voluptatum vero odio ullam omnis!",
        office: "305B",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        key: "Classrooms", position: [-2.5, 0.85, 0.35],
      },
      {
        title: "Room 306 A",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Provident inventore molestias ad quisquam officiis cupiditate itaque sed id quasi quo eveniet, quam unde laboriosam nam voluptatum vero odio ullam omnis!",
        office: "306A",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        key: "Classrooms", position: [0, -0.6, 0.35],
      },
      {
        title: "Room 306 B",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Provident inventore molestias ad quisquam officiis cupiditate itaque sed id quasi quo eveniet, quam unde laboriosam nam voluptatum vero odio ullam omnis!",
        office: "306B",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        key: "Classrooms", position: [-2, -1.1, 0.35],
      },
      {
        title: "Room 306 C",
        description: "Ipomoea aquatica smallanthus sonchifolius.",
        office: "306C",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["13:00AM", "03:00PM"],
        key: "Classrooms", position: [-1, 1, 0.35],
      },
      {
        title: "Room 319",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque ipsa explicabo asperiores? Quibusdam atque ducimus, perferendis, eaque quasi asperiores. Eum obcaecati ut sunt culpa soluta, eius natus reprehenderit itaque quae.",
        office: "319",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["7:30AM", "12:30PM"],
        key: "Classrooms",
        position: [0.83, 1.35, 0.35],
      },
      //! Resources
      {
        title: "Third Floor Stacks",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita nulla pariatur amet id ipsam similique saepe beatae quasi aliquid. Eos fugit esse nesciunt similique maxime, architecto totam ducimus placeat consequatur?",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["7:30AM", "11:30PM"],
        office: "Stacks",
        key: "Resources", position: [-1.67, 2, 0.35],
      },
      //! Labs & Study Areas
      {
        title: "Third Floor Study Area",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat culpa modi nam consequuntur tempora, mollitia eveniet quas alias facere incidunt et, fugit nemo pariatur quia, quasi neque molestias hic maiores.",
        office: "Hall",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "11:30PM"],
        key: "Labs/Study/Areas",
        formattedKey: "Labs & Study Areas", position: [-2.55, 2.15, 0.35,],
      },
      //! Classrooms
      {
        title: "Room 305 A",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Provident inventore molestias ad quisquam officiis cupiditate itaque sed id quasi quo eveniet, quam unde laboriosam nam voluptatum vero odio ullam omnis!",
        office: "305A",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        key: "Classrooms", position: [2.1, 2.1, 0.35,],
      },
      {
        title: "Room 305 B",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Provident inventore molestias ad quisquam officiis cupiditate itaque sed id quasi quo eveniet, quam unde laboriosam nam voluptatum vero odio ullam omnis!",
        office: "305B",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        key: "Classrooms", position: [1.85, 1.25, 0.35],
      },
      {
        title: "Room 306 A",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Provident inventore molestias ad quisquam officiis cupiditate itaque sed id quasi quo eveniet, quam unde laboriosam nam voluptatum vero odio ullam omnis!",
        office: "306A",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        key: "Classrooms", position: [1.3, 2.15, 0.35],
      },
      {
        title: "Room 306 B",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Provident inventore molestias ad quisquam officiis cupiditate itaque sed id quasi quo eveniet, quam unde laboriosam nam voluptatum vero odio ullam omnis!",
        office: "306B",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["8:00AM", "4:30PM"],
        key: "Classrooms", position: [0.15, 2.25, 0.35],
      },
      {
        title: "Room 306 C",
        description: "Ipomoea aquatica smallanthus sonchifolius.",
        office: "306C",
        countryCode: "20",
        phoneNumber: "1021141193",
        openingHours: ["13:00AM", "03:00PM"],
        key: "Classrooms", position: [-1.15, 2, 0.35],
      },
    ]
  },
]
